### ISSUE TITLE
Two bugs

### ISSUE THREAD

**Issue by Ziao** [mapbox/pbf#78] opened 2017-04-05 12:37 UTC
Just a quick heads-up:
- When using a numbered tag higher than 15, PBF will throw errors. Tags starting at 16 should be used to encode less frequently used fields, as the tag takes up two bytes instead of one.
- When using more than 127 repeatable elements, PBF will throw errors like "Uncaught Error: Unimplemented type: 7" or it will parse the fields incorrectly, seemingly at random, even with the exact same input.

Love the library other than that :)

**Comment by kjvalencik** [comment] 2017-04-05 13:00
> When using a numbered tag higher than 15, PBF will throw errors. Tags starting at 16 should be used to encode less frequently used fields, as the tag takes up two bytes instead of one.

Are you able to provide a simple proto file that reproduces this bug? There's only one unit test for this case.
https://github.com/mapbox/pbf/blob/bc2da8f9c9a7a45da50c6c4786016b96fca487a7/test/fixtures/packed_proto3.proto#L20-L22
https://github.com/mapbox/pbf/blob/bc2da8f9c9a7a45da50c6c4786016b96fca487a7/test/compile.test.js#L74-L90

**Comment by kjvalencik** [comment] 2017-04-21 15:51
@Ziao Are you able to provide proto files that reproduce?

**Comment by Ziao** [comment] 2017-06-22 11:03
Sorry for the late reply. I'll upload an example proto file and schema asap.

**Comment by mourner** [comment] 2017-07-07 10:04
Closing this issue because of a lack of reproducible test cases. Will happily reopen once those are provided and verified.

**Closed by mourner** 2017-07-07 10:04 UTC
Labels: question
